### ISSUE TITLE
Quotation marks in example values of the field `filter` cause a syntax error in Swagger UI

### ISSUE THREAD

**Issue by bonaparten** [GIScience/ohsome-api#111]
In Swagger UI, in the endpoint `/elements/count/ratio` quotation marks in the example value of the field `filter2` cause a syntax error.

We should also take a look at the example values in other endpoints.

**Comment by FabiKo117** [comment]
@bonaparten please also give an example of the request or a link to the position where you found it :)

I checked it now and indeed, the escaping of the double quotes is missing in [this](https://api.ohsome.org/v1/swagger-ui.html#/Count/countRatio) swagger example.

But is also seems like now even with escaping, the request does **not** run through, e.g. look at this example:
`https://api.ohsome.org/v1/elements/count/ratio?bboxes=8.625,49.3711,8.7334,49.4397&time=2014-01-01/2017-01-01/P1Y&filter=type:node and \"addr:housenumber=*\"&filter2=type:way&showMetadata=yes`

Am I doing something wrong here @tyrasd?

**Comment by tyrasd** [comment]
I think the quote marks should not be there in the first place. this would be the correct filter: `type:node and addr:housenumber=*`, or if you really want to quote it, then like this: `type:node and "addr:housenumber"=*`

**Comment by FabiKo117** [comment]
Ok yes I am blind.. the marks would just be around the key, not the whole tag. And true, they would not be necessary for this example.

Still, in the docs it's recommended to escape the quotes, but e.g. the following request is not working for me:
`https://api.ohsome.org/v1/elements/count/ratio?bboxes=8.625,49.3711,8.7334,49.4397&time=2014-01-01/2017-01-01/P1Y&filter=\"addr:housenumber\"=*&filter2=type:way&showMetadata=yes`
It works though if I use it without the escape sign. So are quotes now escaped automatically?

**Comment by tyrasd** [comment]
> Still, in the docs it's recommended to escape the quotes

Do you mean here: https://docs.ohsome.org/ohsome-api/v1/filter.html#special-characters-whitespace?

> Escape sequences can be used to represent a literal double-quote character \", while a literal backslash is written as \\.

This refers to when you want to search for tags which _have_ a `"` character in their key or value. One would need to escape those `"` so that they are not mistaken with the quotation marks which are for example used to define strings with whitespaces:

* `name="Heidelberger Brückenaffe"` -> `"` used as quote mark
* `name="Universität \"Ruperto Carola\" Heidelberg"` -> literal `"` within a string needs to be escaped

**Comment by FabiKo117** [comment]
I see.. yes that makes sense, sorry for the missunderstanding. So we would only have to fix then the suggested filter value in the swagger example.
