### ISSUE TITLE
Change default swagger parameters to faster-running examples

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-api#113]
With #111, we found out that the [check-script](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api) wasn't running with the swagger json for a longer time because it takes quite some time to run all different endpoints with their default parameters.

I ran the script with request times. I identified all requests that took longer than 10 seconds with the production-deployed ohsome API:
```txt
GET 200: https://api.ohsome.org/v1/elements/area/ratio/groupBy/boundary?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&filter=type%3Away&filter2=building%3D%2A&format=json&time=2014-01-01%2F2017-01-01%2FP1Y (72.41s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elements/area/ratio/groupBy/boundary (69.71s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'filter': 'type:way', 'filter2': 'building=*', 'format': 'json', 'time': '2014-01-01/2017-01-01/P1Y'}
--------------------------------------------------
GET 200: https://api.ohsome.org/v1/elements/length/ratio/groupBy/boundary?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&filter=type%3Away&filter2=highway%3Dresidential&format=json&time=2014-01-01%2F2017-01-01%2FP1Y (71.57s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elements/length/ratio/groupBy/boundary (68.99s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'filter': 'type:way', 'filter2': 'highway=residential', 'format': 'json', 'time': '2014-01-01/2017-01-01/P1Y'}
--------------------------------------------------
GET 200: https://api.ohsome.org/v1/elements/perimeter/ratio/groupBy/boundary?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&filter=type%3Away&filter2=type%3Away&format=json&time=2014-01-01%2F2017-01-01%2FP1Y (73.57s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elements/perimeter/ratio/groupBy/boundary (73.26s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'filter': 'type:way', 'filter2': 'type:way', 'format': 'json', 'time': '2014-01-01/2017-01-01/P1Y'}
--------------------------------------------------
GET 200: https://api.ohsome.org/v1/elements/bbox?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&clipGeometry=true&filter=type%3Away&properties=tags&time=2016-01-01%2C2017-01-01 (74.53s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elements/bbox (31.46s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'clipGeometry': 'true', 'filter': 'type:way', 'properties': 'tags', 'time': '2016-01-01,2017-01-01'}
--------------------------------------------------
GET 200: https://api.ohsome.org/v1/elements/centroid?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&clipGeometry=true&filter=type%3Away&properties=tags&time=2016-01-01%2C2017-01-01 (31.08s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elements/centroid (31.02s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'clipGeometry': 'true', 'filter': 'type:way', 'properties': 'tags', 'time': '2016-01-01,2017-01-01'}
--------------------------------------------------
GET 200: https://api.ohsome.org/v1/elements/geometry?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&clipGeometry=true&filter=type%3Away&properties=tags&time=2016-01-01%2C2017-01-01 (31.75s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elements/geometry (31.61s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'clipGeometry': 'true', 'filter': 'type:way', 'properties': 'tags', 'time': '2016-01-01,2017-01-01'}
--------------------------------------------------
GET 200: https://api.ohsome.org/v1/elementsFullHistory/bbox?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&clipGeometry=true&filter=type%3Away&properties=tags&time=2016-01-01%2C2017-01-01 (23.07s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elementsFullHistory/bbox (22.91s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'clipGeometry': 'true', 'filter': 'type:way', 'properties': 'tags', 'time': '2016-01-01,2017-01-01'}
--------------------------------------------------
GET 200: https://api.ohsome.org/v1/elementsFullHistory/centroid?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&clipGeometry=true&filter=type%3Away&properties=tags&time=2016-01-01%2C2017-01-01 (22.96s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elementsFullHistory/centroid (22.84s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'clipGeometry': 'true', 'filter': 'type:way', 'properties': 'tags', 'time': '2016-01-01,2017-01-01'}
--------------------------------------------------
GET 200: https://api.ohsome.org/v1/elementsFullHistory/geometry?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&clipGeometry=true&filter=type%3Away&properties=tags&time=2016-01-01%2C2017-01-01 (23.06s)
--------------------------------------------------
POST 200: https://api.ohsome.org/v1/elementsFullHistory/geometry (23.97s)
 → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'clipGeometry': 'true', 'filter': 'type:way', 'properties': 'tags', 'time': '2016-01-01,2017-01-01'}
--------------------------------------------------
```
This is the whole output for comparison: [check-ohsome-api-output.txt](https://github.com/GIScience/ohsome-api/files/5926541/check-ohsome-api-output.txt)

**Comment by tyrasd** [comment]
the `area/ratio` are probably quite slow because of an inefficient implementation in https://github.com/GIScience/ohsome-api/blob/master/src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java#L672-L689: the `combinedFilter` should be used to most efficiently filter the data (instead of the current `exeUtils.newSnapshotFilter(mapRed, filterExpr1, filterExpr2);`). :arrow_left: found by @rtroilo

**Comment by joker234** [comment]
I will create several comments for the specific endpoints (only POST, because I assume GET has the same issue) to discuss better default parameters.
> ```
> POST 200: https://api.ohsome.org/v1/elements/area/ratio/groupBy/boundary (69.71s)
>  → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'filter': 'type:way', 'filter2': 'building=*', 'format': 'json', 'time': '2014-01-01/2017-01-01/P1Y'}
> ```
The first filter calculates the are for up to 41629 ways within this bounding box, the second for up to 24032 buildings. I think this could be the most time-consuming part and would suggest something with less elements, like `'filter': 'building=*', 'filter2': 'building=house'`.

**Comment by joker234** [comment]
> ```
> POST 200: https://api.ohsome.org/v1/elements/length/ratio/groupBy/boundary (68.99s)
>  → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'filter': 'type:way', 'filter2': 'highway=residential', 'format': 'json', 'time': '2014-01-01/2017-01-01/P1Y'}
> ```
same argument as for `/elements/area/ratio/groupBy/boundary`. Even tough there is already a proposed fix (#114), one could use `'filter': 'highway=*', 'filter2': 'highway=residential'` to reduce the amount of elements a little bit and still have a useful example.

**Comment by tyrasd** [comment]
I would still keep at least either a `type:way` (or `geometry:line`) filter, so the query doesn't need to query all nodes and relations as well: `'filter': 'type:way and highway=*', 'filter2': 'type:way and highway=residential'`

**Comment by joker234** [comment]
> ```
> POST 200: https://api.ohsome.org/v1/elements/perimeter/ratio/groupBy/boundary (73.26s)
>  → {'bboxes': '8.625,49.3711,8.7334,49.4397', 'filter': 'type:way', 'filter2': 'type:way', 'format': 'json', 'time': '2014-01-01/2017-01-01/P1Y'}
> ```
same argument as for `/elements/{area,length}/ratio/groupBy/boundary`, but maybe select a more useful then two times the same filter ;) E.g. `'filter': 'building=university', 'filter2': 'building=church'`.

**Comment by joker234** [comment]
for all other issues, `/elements{,FullHistory}/{bbox,centroid,geometry}`, I would suggest a filter that has a smaller amount of results then `type:way`, like `building=university`.

**Comment by FabiKo117** [comment]
Good issue. We never really checked that how long the requests with these example values in swagger actually take. Another idea would also be to shrink the default bbox a bit, so that there are less features in general inside and make sure to always have a filter on the OSM type as @tyrasd suggested. Combined with the fixed /ratio computation, I guess those things should already be sufficient.
