### ISSUE TITLE
Error "Failed to execute query because cache partition has been lost"

### ISSUE THREAD

**Issue by tuukka** [GIScience/ohsome-api#140]
Since yesterday, I'm getting the following error response for some API requests:

> "Failed to obtain remote job result policy for result fromComputeTask.result(..) method due to undeclared user exception (will fail the whole task): GridJobResultImpl [job=org.heigit.bigspatialdata.oshdb.api.mapreducer.backend.OSHDBIgniteMapReduceComputeTask$1@41d3007, sib=GridJobSiblingImpl [sesId=28bbd05d771-7c99ebfe-a735-4696-b785-18ce303cdbd6, jobId=38bbd05d771-7c99ebfe-a735-4696-b785-18ce303cdbd6, nodeId=e93a1069-ce66-4ccc-b464-5f3b948f068d, isJobDone=false], jobCtx=GridJobContextImpl [jobId=38bbd05d771-7c99ebfe-a735-4696-b785-18ce303cdbd6, timeoutObj=null, attrs=HashMap {}], node=TcpDiscoveryNode [id=e93a1069-ce66-4ccc-b464-5f3b948f068d, consistentId=cbda9cd9-d263-4ae4-9615-aa1dce5a2485, addrs=ArrayList [0:0:0:0:0:0:0:1%lo, 127.0.0.1, 193.197.73.181], sockAddrs=HashSet [/0:0:0:0:0:0:0:1%lo:47500, /127.0.0.1:47500, /193.197.73.181:47500], discPort=47500, order=36, intOrder=20, lastExchangeTime=1614357951328, loc=false, ver=2.9.0#20201015-sha1:70742da8, isClient=false], ex=class org.apache.ignite.compute.ComputeUserUndeclaredException: Failed to execute job due to unexpected runtime exception [jobId=38bbd05d771-7c99ebfe-a735-4696-b785-18ce303cdbd6, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=org.heigit.bigspatialdata.oshdb.api.mapreducer.backend.OSHDBIgniteMapReduceComputeTask, dep=SharedDeployment [rmv=false, super=GridDeployment [ts=1614358339963, depMode=SHARED, clsLdr=GridDeploymentClassLoader [id=1333b3fd771-e93a1069-ce66-4ccc-b464-5f3b948f068d, singleNode=false, nodeLdrMap=HashMap {7c99ebfe-a735-4696-b785-18ce303cdbd6=390c805d771-7c99ebfe-a735-4696-b785-18ce303cdbd6}, p2pTimeout=60000, usrVer=0, depMode=SHARED, quiet=false], clsLdrId=1333b3fd771-e93a1069-ce66-4ccc-b464-5f3b948f068d, userVer=0, loc=false, sampleClsName=org.heigit.bigspatialdata.oshdb.api.mapreducer.backend.OSHDBIgniteMapReduceComputeTask, pendingUndeploy=false, undeployed=false, usage=2]], taskClsName=org.heigit.bigspatialdata.oshdb.api.mapreducer.backend.OSHDBIgniteMapReduceComputeTask, sesId=28bbd05d771-7c99ebfe-a735-4696-b785-18ce303cdbd6, startTime=1614368810059, endTime=9223372036854775807, taskNodeId=7c99ebfe-a735-4696-b785-18ce303cdbd6, clsLdr=GridDeploymentClassLoader [id=1333b3fd771-e93a1069-ce66-4ccc-b464-5f3b948f068d, singleNode=false, nodeLdrMap=HashMap {7c99ebfe-a735-4696-b785-18ce303cdbd6=390c805d771-7c99ebfe-a735-4696-b785-18ce303cdbd6}, p2pTimeout=60000, usrVer=0, depMode=SHARED, quiet=false], closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, internal=false, topPred=ContainsNodeIdsPredicate [], subjId=7c99ebfe-a735-4696-b785-18ce303cdbd6, mapFut=IgniteFuture [orig=GridFutureAdapter [ignoreInterrupts=false, state=INIT, res=null, hash=940331953]], execName=null], jobId=38bbd05d771-7c99ebfe-a735-4696-b785-18ce303cdbd6], err=javax.cache.CacheException: class org.apache.ignite.internal.processors.cache.CacheInvalidStateException: Failed to execute query because cache partition has been lostParts [cacheName=global-74030_grid_node, part=2000]], hasRes=true, isCancelled=false, isOccupied=true]"
> ​​
> path: "/elements/count"
> ​​
> status: 500
> ​​
> timestamp: "2021-02-26T19:46:50.194+0000"

**Comment by FabiKo117** [comment]
Hi @tuukka,

thanks for reporting your issue. Can you quickly tell me if it still persists? And if so - can you provide the exact request details, meaning including the parameters that you've used?

**Comment by tuukka** [comment]
I'm not getting errors anymore - thanks! Some of the most recent data seems to have disappeared though: `time=//P1D` used to return data up to 2021-02-21 but now up to 2021-02-14. Also, queries that took 2 minutes now take 4 or 5. For example, now it takes 562 seconds to fetch https://api.ohsome.org/v1/elements/count?showMetadata=true&filter=entrance=*&time=%2F%2FP1D&bboxes=-180%2C-90%2C180%2C90

**Comment by FabiKo117** [comment]
Alright, glad to hear that.

About the timestamp within the data: We had to perform a fallback to an older data set as we experienced some issues (your reported one was one of them). Right now, there's a newer data set again in place having the follwing end timestamp: `2021-02-28T21:00Z`. You can always find infos on the currently in-use OSHDB dataset under the following URL: https://api.ohsome.org/v1/metadata

About the response time: This usually depends on how many people are currently accessing/working with the ohsome API and the cluster behind and therefore can vary. We have our own little server infrastructure, where we run our database, but also other computations. 

A general tipp: try to always include the OSM type or geometry type into your filter to make your query more performant, e.g. something like `type:node` if you're just interested in nodes, or `geometry:polygon` if you are interested in polygonal features. See https://docs.ohsome.org/ohsome-api/v1/filter.html for more infos.
