### ISSUE TITLE
[documentation] enhance error / response code documentation

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-api#150]
Currently, we don't have any documentation what errors a user can expect. [http-response-status.rst](https://github.com/GIScience/ohsome-api/blob/bbfbdf33066065103de7da8f7fffa0d14fc92065/docs/http-response-status.rst) provides a good, brief documentation on the status codes. This can be enhanced with all(?) specific errors, the ohsome API is able to return (with the exception of 500 internal errors, that are caused by other components).

Examples:
 * The 404 should mention the case when the time/area is not covered.
 * 401 isn't supported at the moment, correct?

**Comment by FabiKo117** [comment]
With the PR tackling this issue, we should also add a note to the 200 response code regarding the special case when an error occurs during the processing of a data-extraction request. So that the result is then a broken GeoJSON containing the error JSON object at the end.
