### ISSUE TITLE
Copy issue templates from other projects

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-api#153]
Copying the issue templates from https://github.com/GIScience/oshdb to this project may improve the quality of reported issues.

**Comment by bonaparten** [comment]
We decided a couple of weeks ago to not use an issue template for the ohsome API. But we can discuss it again if it is requested.

**Comment by SlowMo24** [comment]
Ah, I was not aware of that discussion. I ALWAYS miss some guidance when creating issues and also find it handy to have a distinction between issues and requests.

**Comment by bonaparten** [comment]
No problem. You are probably right!
