### ISSUE TITLE
Query crashes when using non-existent tag in filter

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-api#154]
# Problem

The following query filters for the non-existing tag `hngkkk=lkjfuur`: https://api.ohsome.org/v1/elements/count?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&filter=type%3Away%20and%20hngkkk%3Dlkjfuur&format=json&time=2014-01-01%2F2017-01-01%2FP1Y

This returns 
```
{
  "timestamp": "2021-03-18T14:06:22.487+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Unable to find tag id -934710090=-230516983 in keytables.",
  "path": "/elements/count"
}
```

This poses the following problems:

- wrong hint to cause of error: The error is a 4xx user error of wrong input, no fault on the server side
- the error is very similar to the error returned by a broken keytables database. Two different issues creating the same error result is not desirable
- no support is given to the user on how to solve that issue

# Possible solution

Provide a better error response such as 

```
{
  "timestamp": "2021-03-18T14:06:22.487+0000",
  "status": 400, (https://www.restapitutorial.com/httpstatuscodes.html)
  "error": "Bad Request/Invalid Input",
  "message": "Unable to find tag ihngkkk=lkjfuur. This tag does not exist in the OSM full history. (optional): did you mean ... 'closest tag'",
  "path": "/elements/count"
}
```

# Alternative solution

Ignore wrong input and notify user. This may actually be a solution because strictly speaking any tag is allowed so the query could refer to a tag the was first used after the latest state of the oshdb or even in the future when creating a query for a tag that will be implemented soon (like a name or hashtag or anything).

**Comment by SlowMo24** [comment]
#150 is related

**Comment by bonaparten** [comment]
It doesn't seem possible to me to check all tags and offer a suggestion about the right tag.
The exception comes directly from the oshdb. We can catch the exception in the ohsome API and throw a BadRequestException.

**Comment by SlowMo24** [comment]
> It doesn't seem possible to me to check all tags and offer a suggestion about the right tag.

yes, I wasn't really serious there.

> The exception comes directly from the oshdb. We can catch the exception in the ohsome API and throw a BadRequestException.

I remeber also coming accross that oshdb error also. So it would be great to fix this here but also create an upstream issue to improve the upstream error message aswell.

**Comment by tyrasd** [comment]
This is a bug. But the solution should not be to return an error code, but instead to return an empty result.

Here's one reason: Let's say a user wants to query for a very specific tag (e.g. [`short_name=HeiGIT`](https://taginfo.openstreetmap.org/tags/short_name=HeiGIT), which is only present in specific extracts (e.g. `heidelberg.mv.db` or `germany.oshdb.mv.db`) and not present in other extracts (e.g. `buxtehude.oshdb.mv.db`). When a user performs a query on a bbox using the germany extract, they will get an empty result if the query bbox is somewhere outside of Heidelberg. The same empty result would also be expected for when the same query is run using the `buxtehude` extract.∎

**Comment by FabiKo117** [comment]
This also sounds quite new to me, cause I remember that in the past I always got an empty result for non-existing tags. I used that quite often to just quickly check the response format for example, so there is not much computation involved and I get a fast response.

**Comment by SlowMo24** [comment]
> No. The solution should not be to return an error code or to arbitrarily ignore user input, but instead to return an empty result.

Good point but I would always go for the most informative and user friendly solution. There should definitely be a warning to the user like ' tag ... not present in extract'. Silently returning nothing will create confusion, even if that was the correct behaviour.

How about enhancing the returned json-format and adding a jeson object "warnings" just as the "licence" to contains such information?

**Comment by tyrasd** [comment]
A warning might be quite neat. The OSHDB does something similar (see [here](https://github.com/GIScience/oshdb/blob/0.6.3/oshdb-api/src/main/java/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.java#L481)).

But at the moment I don't know of an easy way to implement that. I'll keep it in mind.

**Comment by SlowMo24** [comment]
ah yes, there is not basis of communication between the OSHDB and ohsome-api on those matters. Lets teach them some manners :-)
