### ISSUE TITLE
finalize and document "unclipped geometry mode"

### ISSUE THREAD

**Issue by tyrasd** [GIScience/ohsome-api#20]
In v1.0, there exists an (undocumented) feature flag in the data extraction endpoints, which disables the clipping to the query area-of-interest of the geojson feature geometries.

[The currently undocumented implementation of having it mixed up into the `properties` parameter is not great, because this parameter should just alter the `properties` of the returned GeoJSON, nothing more but also nothing less than that. `unclipped` doesn't fit into this parameter, because it alters the `geometry` of the resulting GeoJSON.]

In order to complete this feature, we need to:
 
* [ ] choose and create a dedicated parameter for it
* [ ] add it to the documentation

see also https://github.com/GIScience/ohsome-api/pull/18#issuecomment-663558742

**Comment by FabiKo117** [comment]
To add: the former usage of the unclipped functionality inside the properties parameter will be supported until the next major release, but it will remain undocumented as the recommended way to use it should be through the new parameter.
