### ISSUE TITLE
enhance /users/count endpoint with contributionType parameter

### ISSUE THREAD

**Issue by tyrasd** [GIScience/ohsome-api#224]
### Use Case Description
To analyze user activity with respect to different contribution patterns, it could be useful to narrow down user counts by contribution type, like already implemented for the contribution count endpoints in #198.

### Request Description
The `/users/count` endpoint would return the number of users which performed at least one creation/deletion/*modification operation during the respective time intervals of the query. These numbers would be typically only slightly lower than the "unfiltered" total user count.

**Comment by bonaparten** [comment]
Should it be implemented only for the endpoint `/users/count` or is there some use case also for the other resources ( `/users/{resource}` )?

**Comment by tyrasd** [comment]
I guess it would make sense for all `/users` endpoints, i.e.:

```
/count
/count/groupBy/(boundary, key, tag or type)
/count/density
/count/density/groupBy/(boundary, tag or type)
```
