### ISSUE TITLE
api.ohsome.org is not working

### ISSUE THREAD

**Issue by frafra** [GIScience/ohsome-api#248]
I am not sure if this is the right place for reporting such kind of issues, but the api.ohsome.org server has not been replying properly since last weekend. I set up a monitoring system after a while just to be keep track of the outage: https://github.com/frafra/ohsome-api-upptime/issues/1

**Comment by bonaparten** [comment]
Thanks for your post. Please consider sending us an email instead of opening an issue for such cases (ohsome(at)heigit(dot)org). The ohsome API was down but it should work fine now.
I close the issue.
