### ISSUE TITLE
ohsome api documentation examples

### ISSUE THREAD

**Issue by ManuelKraft** [GIScience/ohsome-api#286]
I suggest to add examples in the ohsome api documentation for users who use the ohsome package. For people who completely orientate on the documentation and are not sure whether they should install the ohsome package or not it is a nice prove that using the ohsome package is way more efficient and way more suggested than working only with requests.

**Comment by joker234** [comment]
Thanks for your suggestion. The ohsome-py packages is still in an Experimental status and depends on large dependencies like (geo)pandas. Therefore we currently suggest to use more lightweight python packages like `requests`. If you want to make a suggestion feel free to add a comment in the docs or README.md that mentions ohsome-py in a Pull Request.
