### ISSUE TITLE
Internal Server Error when using `changeset:…` filter in non-contribution views

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-api#289]
### Bug Description
When using non-contribution views (i.e. `/elements/count`) you get an `Internal Server Error` without a proper error message when a changeset filter is set (i.e. `changeset:123`).

### General Information
Please include the following general information about the issue and list any additional steps needed to reproduce the bug.
 - Version of the ohsome API: 1.8.0
 - Which API instance was requested [e.g. remote instance at `https://api.ohsome.org/v1`, local instance with an h2 file or connected to the cluster, etc.]: https://api.ohsome.org/v1
 - Affected endpoint(s) [e.g. /contributions/count]: at least `/elements/count`
 - URL of your request (and request body if applicable): https://api.ohsome.org/v1/elements/count?bboxes=8.67%2C49.39%2C8.71%2C49.42&filter=type%3Away%20and%20geometry.squareness%3A(0.8..)&format=json&time=2022-01-01
 - Used HTTP method [GET or POST]: GET (but is independent)
 - Utilized tool/library for the request [e.g. cURL, Postman, ohsome-py, etc.]: swagger-ui (but is independent)

### Expected Behaviour
Throwing a proper error message

#### Error Messages, Logs, Screenshots
```
{
  "timestamp": "2023-01-04T12:55:58.576+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "path": "/elements/count"
}
```

**Comment by tyrasd** [comment]
odd. I can't reproduce the issue with a simple filter like `type:way and changeset:1`

https://api.ohsome.org/v1/elements/count?bboxes=8.67%2C49.39%2C8.71%2C49.42&filter=type:way%20and%20changeset:1&format=json&time=2022-01-01

**Comment by tyrasd** [comment]
ah ok, I see now that the error only occurs if the bbox+filter combination includes any "potentially" matching objects. Like in this query:

https://api.ohsome.org/v1/elements/count?bboxes=8.67%2C49.39%2C8.71%2C49.42&filter=type:way%20and%20changeset:55639048&format=json&time=2022-01-01
