### ISSUE TITLE
Improve wording of documentation for groupByKeys

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-api#296]
### Use Case Description

`:query groupByKeys: OSM key(s) given as a list and combined with the ‘AND’ operator; default: empty;` in https://github.com/GIScience/ohsome-api/blob/master/docs/group-by.rst#L28 is difficult to understand (and possibly wrong?). I don't think there is a need to be this short.

### Request Description

Suggested update: 

`:query groupByKeys: OSM key(s) given as a comma separated list like "key1,key2...". default: empty;` 

The description should additionally contain the following text, but that may be put into the main description of the function:

`The result will contain separate results for each key and the 'remainder' meaning all objects that fulfilled the filter but had none of the 'groupByKeys'`.

### Additional Information

Similar text also occurs in other locations.

//cc @redfrexx

**Comment by tyrasd** [comment]
Thanks for the hint @SlowMo24. The descriptions were actually wrong. The _combined with the AND operator_ part was probably a copy-paste mistake when first assembling the docs here. See #297 for a proposed fix.

> Similar text also occurs in other locations.

I found two more occurrences in the same file. Are there also other documentation files where parameters are wrongly described?
