### ISSUE TITLE
Detailed modification counts

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/ohsome-api#31]
Having an additional filter to get counts of features by contribution type (creation/modification/…/deletion).

**Comment by FabiKo117** [comment]
This could also be extended to incorporate the # of users, so e.g. how many users were performing a creation.

**Comment by FabiKo117** [comment]
This feature will be included in the endpoint `/contributions/count/groupBy/contributionType` and also within `/users/count/groupBy/contributionType`, which will be most likely the next 2 new upcoming endpoint grouping types.

**Comment by tyrasd** [comment]
partially implemented in https://github.com/GIScience/ohsome-api/pull/162 and https://github.com/GIScience/ohsome-api/pull/198

**Comment by tyrasd** [comment]
let's continue the remaining part of this enhancement in https://github.com/GIScience/ohsome-api/issues/224
