### ISSUE TITLE
When entering a list of Grouping Values: Unable to use a value containing a " " space

### ISSUE THREAD

**Issue by TLDuhamel** [GIScience/ohsome-api#313]
I am running [this ohsome dashboard query](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=tag&time=2007-10-08T00%3A00%3A00Z%2F2023-08-10T20%3A00Z%2FP1M&measure=count&groupByKey=source&groupByValues=LINZ%2CAuckland+Council&key=building&value=&types=way&adminids=-556706), to generate an OSM History graph of buildings with certain values in their source tag.

One of the source tag values I am interested in is `Auckland Council`. If I enter this string alone as the only Grouping Value, [it works fine](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=tag&time=2007-10-08T00%3A00%3A00Z%2F2023-08-10T20%3A00Z%2FP1M&measure=count&groupByKey=source&groupByValues=test%2CAuckland+Council&key=building&value=&types=way&adminids=-556706).

However, when I want to group on multiple values, I can provide a comma delimited list of values into the Grouping Values field eg `LINZ,Auckland Council,Bing`. But the result is that the space in the middle of the string is dropped, and the query then searches for `LINZ`, `AucklandCouncil` and `Bing`.

I have tried to [surround the string in quotes](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=tag&time=2007-10-08T00%3A00%3A00Z%2F2023-08-10T20%3A00Z%2FP1M&measure=count&groupByKey=source&groupByValues=LINZ%2C%22Auckland+Council%22%2CBing&key=building&value=&types=way&adminids=-556706), but that does not work.

**Comment by suyash8991** [comment]
https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=tag&time=2007-10-08T00%3A00%3A00Z%2F2023-08-10T20%3A00Z%2FP1M&measure=count&groupByKey=source&groupByValues=LINZ%2CAuckland+Council&key=building&value=&types=way&adminids=-556706
I ran this same query and it still seems to remove space from the Auckland Council and generate no data

**Comment by joker234** [comment]
> https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=tag&time=2007-10-08T00%3A00%3A00Z%2F2023-08-10T20%3A00Z%2FP1M&measure=count&groupByKey=source&groupByValues=LINZ%2CAuckland+Council&key=building&value=&types=way&adminids=-556706 I ran this same query and it still seems to remove space from the Auckland Council and generate no data

Thanks @suyash8991 for letting us know. The original issue was addressed in PR #314 which is merged but still not released and therefore also not deployed, yet. We'll let you know when the fixes will be released and deployed.
