### ISSUE TITLE
Inconsistency in timestamps: some with, some without time zone

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-api#318]
### Bug Description

The endpoint `elements/count/groupBy/boundary` returns timestamps with timezone

https://api.ohsome.org/v1/elements/count/groupBy/boundary?bboxes=8.67%2C49.39%2C8.71%2C49.42&filter=geometry%3Apoint%20and%20natural%3Dtree&time=2014-01-01

<details>
<summary>Response</summary>

```json
{
  "attribution": {
    "url": "https://ohsome.org/copyrights",
    "text": "© OpenStreetMap contributors"
  },
  "apiVersion": "1.10.1",
  "groupByResult": [
    {
      "groupByObject": "boundary1",
      "result": [
        {
          "timestamp": "2014-01-01T00:00:00Z",
          "value": 850
        }
      ]
    }
  ]
}
```

</details>

while the endpoint `elements/count/ratio/groupBy/boundary` returns timestamps without timezone

https://api.ohsome.org/v1/elements/count/ratio/groupBy/boundary?bboxes=8.67%2C49.39%2C8.71%2C49.42&filter=geometry%3Apoint%20and%20natural%3Dtree&filter2=geometry%3Apoint%20and%20shop%3Dbakery&format=json&time=2014-01-01

<details>
<summary>Response</summary>

```json
{
  "attribution": {
    "url": "https://ohsome.org/copyrights",
    "text": "© OpenStreetMap contributors"
  },
  "apiVersion": "1.10.1",
  "groupByBoundaryResult": [
    {
      "groupByObject": "boundary1",
      "ratioResult": [
        {
          "timestamp": "2014-01-01T00:00:00",
          "value": 850,
          "value2": 28,
          "ratio": 0.032941
        }
      ]
    }
  ]
}
```

</details>

### General Information

 - Version of the ohsome API: `1.10.1`
 - API instance `https://api.ohsome.org/v1`
 - Affected endpoint: I have only teste `elements/count/ratio/groupBy/boundary`
 - URL of your request (and request body if applicable): see above
 - Used HTTP method: GET but it should not matter
 - Utilized tool/library for the request: swagger or curl, should not matter

### Expected Behaviour

Either always return a time zone, or never (which I would prefer).

#### Error Messages, Logs, Screenshots

None

#### Additional Information

None

### Notes

None

//cc @rp280

**Comment by tyrasd** [comment]
At first glance, it seems that the `/elements/(aggregation)/ratio/groupBy/boundary` is the only endpoint which does not return a timestamp with explicit `Z` timezone. The [documentation](https://docs.ohsome.org/ohsome-api/v1/endpoints.html#) has also always included the timezone in the examples. I agree that we should consistently always return the same format, but to limit the scope of the fix, let's stick to the format including the `Z`.
