### ISSUE TITLE
500 internal server error reports

### ISSUE THREAD

**Issue by qnguvwu1** [GIScience/ohsome-api#327]
Hi, thank you for hosting this interesting project!

While using the OhSome API, we found 20 500 status codes, so I am reporting them with reproduce command

1. curl -X GET https://api.ohsome.org/v1/users/count/groupBy/boundary?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397 
2. curl -X POST https://api.ohsome.org/v1/users/count/density?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397
3. curl -X POST https://api.ohsome.org/v1/users/count/density/groupBy/boundary?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397    
4. curl -X GET https://api.ohsome.org/v1/elements/perimeter/groupBy/boundary/groupBy/tag?filter=type%3Dway+and+building%3Dyes&format=geojson&groupByKey=boundary1&bcircles=8.625%2C49.3711%2C5000 
5. curl -X POST https://api.ohsome.org/v1/users/count/groupBy/type?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397 
6. curl -X GET https://api.ohsome.org/v1/users/count?bboxes=12.000%2C54.000%2C12.100%2C54.100  
7. curl -X POST https://api.ohsome.org/v1/users/count/groupBy/key?bboxes=12.0%2C48.0%2C12.1%2C48.1&filter=type%3Arelation&format=geojson&groupByKeys=building&timeout=60   
8. curl -X POST https://api.ohsome.org/v1/elements/area/groupBy/tag?bboxes=13.0%2C45.0%2C13.1%2C45.1&groupByKey=building&keys=&time=2018-01-01%2F2021-01-01%2FP1Y  
9. curl -X GET https://api.ohsome.org/v1/users/count/density?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397     
10. curl -X POST https://api.ohsome.org/v1/elements/area/groupBy/boundary?bpolys=8.625%2C49.3711%2C8.7334%2C49.4397%2C8.625%2C49.3711&format=json&keys=&time=2014-01-01%2F2017-01-01%2FP1Y   
11. curl -X POST https://api.ohsome.org/v1/users/count?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397   
12. curl -X GET https://api.ohsome.org/v1/users/count/density/groupBy/type?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397    
13. curl -X POST https://api.ohsome.org/v1/users/count/density/groupBy/type?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397     
14. curl -X POST https://api.ohsome.org/v1/elements/area/ratio?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&filter2=type%3Arelation+and+building%3D%2A&keys=&time=2014-01-01%2F2017-01-01%2FP1Y&timeout=30&types=&types2=&values=&values2=
15. curl -X POST https://api.ohsome.org/v1/users/count/groupBy/boundary?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397  
16. curl -X GET https://api.ohsome.org/v1/users/count/groupBy/type?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397   
17. curl -X  POST https://api.ohsome.org/v1/elements/length/density/groupBy/tag?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397&groupByKey=boundary&keys=&time=2014-01-01%2F2017-01-01%2FP1Y&values= 
18. curl -X GET https://api.ohsome.org/v1/users/count/density/groupBy/boundary?bboxes=8.625%2C49.3711%2C8.7334%2C49.4397  
19. curl -X GET https://api.ohsome.org/v1/elements/length/groupBy/boundary/groupBy/tag?bpolys=8.620%2C49.370%2C8.730%2C49.435%2C8.720%2C49.375%2C8.620%2C49.370&format=geojson&groupByKey=highway&keys=filter&time=2014-01-01%2F2017-01-01%2FP1Y&timeout=30
20. curl -X POST https://api.ohsome.org/v1/elements/length?bboxes=14.625%2C55.3711%2C14.7334%2C55.4397&format=json&keys=&showMetadata=true&timeout=540&types=

**Comment by tyrasd** [comment]
This bug is likely related to (and fixed by) https://github.com/GIScience/oshdb/pull/529

**Comment by tyrasd** [comment]
This is now fixed in ohsome-api version 1.10.3 (thanks to OSHDB version 1.2.3). Note that the above queries are still very slow (likely running into timeouts), as they don't specify any `filter`.
