### ISSUE TITLE
Missing tags while extracting features with geometries

### ISSUE THREAD

**Issue by vwvbrand** [GIScience/ohsome-api#332]
### Use Case Description
Extracting road features with geometries and attribute data (width) to buffer and create polygonal geometries. It would be useful to enrich existing timeseries of land-use/land-cover datasets that mostly based on remote sensing data (for example, [UKCEH land-cover](https://www.ceh.ac.uk/data/ukceh-land-cover-maps).

### Request Description
Only limited number of tags is returned for POST/elements/(geometryType) when trying to fetch tags. Currently it is specified as "properties" : "tags". It would be more useful to bring all the tags available from OSM (or,  at least, specify needed, for example, "properties" : "width").

### Additional Information
For the sample request with a simple filter for road features, the query brings only 127 tags (compared to raw data fetched through [Overpass Turbo API](https://overpass-turbo.eu/) - 612 tags). 
<img width="303" alt="Capture_1" src="https://github.com/user-attachments/assets/b2176c0f-f944-494d-a81b-d28fffae7259">
<img width="359" alt="Capture_2" src="https://github.com/user-attachments/assets/95c60e32-2444-44ed-8ab4-19b89b1fe3b8">

The Python code used is the following (template bounding bbox from Ohsome API documentation):
`
url = 'https://api.ohsome.org/v1/elements/geometry'
data = {"bboxes": "8.625,49.3711,8.7334,49.4397", "properties": "tags", "time": "2024-01-01", "filter": "highway=tertiary"}
response = requests.post(url, data=data)
print(response.json())
`

'Width' column persists in the 2023-2024 timestamp, but omitted from the earlier timestamps, which complicates the analysis of historical land use change.

**Comment by tyrasd** [comment]
> For the sample request with a simple filter for road features, the query brings only 127 tags (compared to raw data fetched through [Overpass Turbo API](https://overpass-turbo.eu/) - 612 tags).

I cannot really replicate this behaviour. When selecting features from overpass using the same filters, bbox and time parameter (https://overpass-turbo.eu/s/1Q62), there are also exactly 127 tags returned.

> 'Width' column persists in the 2023-2024 timestamp, but omitted from the earlier timestamps

This is also the case when querying with overpass: https://overpass-turbo.eu/s/1Q5Y

**Comment by tyrasd** [comment]
> Only limited number of tags is returned […] It would be more useful to bring all the tags available from OSM 

The ohsome-api returns all tags that are present on the returned features. It is not practical to return _all_ tags available in OSM, as that would mean that every query would have to return hundreds of thousands of tags (see [taginfo](https://taginfo.openstreetmap.org/keys)).
