### ISSUE TITLE
Data extraction: handling of tags that have same key as a property (e.g. @osmId)

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/ohsome-api#40]
As raised in a [discussion](https://github.com/GIScience/ohsome-api/issues/23#issuecomment-682455373) in another issue, how should we deal with tags that also start with the "@" sign?

Escaping them through adding a 2nd @ could be a good way to go. This would only be necessary though on tags that have the same name as one of our property, e.g. the `@osmId` tag and not on all tags starting with @.

**Comment by joker234** [comment]
Thanks for excluding that from the other issue.

I would suggest to change all keys matching `^@` to `@@`, document that, and for the very rare cases someone wants to use that tags, we don't have a problem there.

**Comment by FabiKo117** [comment]
Yeah we could also do it like that. As you say it would then just be important to document it properly, because if the user would request then for ```@``` the response actually has ```@@``` at the start of the tag.
