### ISSUE TITLE
Ignore space within/before/after brackets in filter syntax

### ISSUE THREAD

**Issue by kathap** [GIScience/ohsome-api#56]
For the filter it would be practical if spaces within the brackets or in bewteen were ignored, for example `type:way and ( highway=footway and motor_vehicles=no) or(highway=service)`

**Comment by tyrasd** [comment]
moved to https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/libs/ohsome-filter/-/issues/7
