### ISSUE TITLE
accept empty filter parameter in id:

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-api#65]
The following query results in code `400` I would expect it to not filter for ids.

`(landuse=* or natural=* or waterway=*) and geometry:polygon and ((not id:() and type:way) or (not id:() and type:relation))`

**Comment by SlowMo24** [comment]
also only 0 is accepted as dummy value (no id<0)

**Comment by FabiKo117** [comment]
I don't quite get why you want to specifically "not filter for ids". If you don't specify any id filter, than automatically you don't filter for them, i.e. the id is irrelevant.

**Comment by SlowMo24** [comment]
yes, I understand this seems odd. It happened in an automated environment where I query data for different regions but want to ignore data that I already have. Sometimes I have no data for a region resulting in the above filter. You can decide if you want to close this as no-fix.

**Comment by tyrasd** [comment]
@SlowMo24 https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/libs/ohsome-filter/-/issues would be the right place to discuss this
