### ISSUE TITLE
Your ohsome API instance return single error on all example requests 

### ISSUE THREAD

**Issue by mois-ilya** [GIScience/ohsome-api#68]
On all requests to your server returns error **`The timerange metadata could not be retrieved from the db.`**

Example request (from manual) `https://api.ohsome.org/v1/elements/area?bboxes=8.625,49.3711,8.7334,49.4397&format=json&time=2014-01-01&filter=landuse=farmland and type:way`

Server response:
`{
    "timestamp": "2020-11-03T01:48:23.125+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "The timerange metadata could not be retrieved from the db.",
    "path": "/elements/area"
}`

Request from python  gives the same result

**Comment by FabiKo117** [comment]
Hi, thanks for reporting this issue. This was just a temporary condition though, as one of our backend databases did not have enough disk space left, so the API crashed. Everything should work now again as expected.
