### ISSUE TITLE
Lombok hides Javadoc for public getter&setter

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/ohsome-api#74]
See the following 2 Javadocs for the same class:

v1.1.1:
https://docs.ohsome.org/java/ohsome-api/1.1.1/org/heigit/ohsome/ohsomeapi/inputprocessing/ProcessingData.html

v1.2.0:
https://docs.ohsome.org/java/ohsome-api/1.2.0/org/heigit/ohsome/ohsomeapi/inputprocessing/ProcessingData.html

additional info: https://projectlombok.org/features/GetterSetter

**Comment by joker234** [comment]
Maybe a solution would be to delombok the code:
>  There is a plugin for Maven that we recommend you use if you want to delombok via maven. Useful if you want to run source analysis tools on your source after lombok has been applied, or if you want to generate javadoc. The plugin is open source. Read more about the lombok maven plugin. 

Source: https://projectlombok.org/setup/maven
