### ISSUE TITLE
Refactor DataExtractionTransformer.java

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-api#76]
#75 introduced the new class `DataExtractionTransformer.java`. This was a hotfix fixing the non-serializability of some classes making the ohsome API's `/elemensFullHistory` endpoint unable to work with ignite.

The new class has to be refactored, especially:
* [ ]  Add javadoc
* [ ]  Refactor variables, input parameters of the constructor
* [ ]  Fix other Issues (e.g. from SonarLint)
* [ ]  Unit Tests?

**Comment by tyrasd** [comment]
most of this should be addressed with https://github.com/GIScience/ohsome-api/pull/178. proper dedicated unit tests would be nice, but from what I can see, the integration tests already cover this class quite well: https://jenkins.ohsome.org/job/ohsome-api/job/master/515/jacoco/org.heigit.ohsome.ohsomeapi.executor/DataExtractionTransformer/
