### ISSUE TITLE
Providing /contributions response as a downloadable file

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/ohsome-api#77]
The response of the newly implemented ```/contributions/(latest)/geometry|bbox|centroid``` endpoints can also get quite big. Therefore, it would make sense to provide it in the compressed gzip format, as it is already done with responses for the /elements and /elementsFullHistory endpoints. 

The following lines in the RequestFilter.java class would have to be extended to also support the /contributions:
https://github.com/GIScience/ohsome-api/blob/d890d5d9399b69b3dc4e1e7b759dd13e87105c99/src/main/java/org/heigit/ohsome/ohsomeapi/filter/RequestFilter.java#L48

**Comment by tyrasd** [comment]
this was fixed by #78, right?

**Comment by FabiKo117** [comment]
@tyrasd Yes, I forgot to close it with the PR..

Fixed with #78
