### ISSUE TITLE
Postman collection used for testing

### ISSUE THREAD

**Issue by AML14** [GIScience/ohsome-api#85]
Hey there,

Thanks for the API, I really like it. I was able to deploy it on my machine following the steps on the README and everything is working fine.

Towards the end of the README, I saw that you are using Postman to test the API. Would it be possible to get access to such Postman collection? I'd like to see a few request/response examples and experiment with them.

Thanks in advance.

Alberto.

**Comment by FabiKo117** [comment]
Hey Alberto,

thanks for trying out our API.

Indeed we were/are using Postman, but mostly during the development phase when we were implementing new endpoints and parameters and tested them. They are also scattered in different collections, focused on small regions, and mostly worked with an older version of the API, so I'm not sure how valuable they would be for you.

The current tests are all inside the [Java code](https://github.com/GIScience/ohsome-api/tree/master/src/test/java/org/heigit/ohsome/ohsomeapi), where we have over 200 different tests. In our [docs](https://docs.ohsome.org/ohsome-api/v1/endpoints.html), you can also find different use case examples for the available endpoints.

Hope the provided information can also help you out.

Best wishes,
Fabian
